site_name: "infisical-httpx-sdk"
repo_url: "https://github.com/riebecj/infisical-httpx-sdk"
site_dir: "docs"
docs_dir: "gh-pages"

watch:
  - src/infisical

extra_css:
  - stylesheet.css

nav:
  - Home: README.md
  - Clients: 
    - Base: src/infisical/clients/base.md
    - Sync/Async: src/infisical/clients/clients.md
  - Credentials:
    - Providers: src/infisical/credentials/providers.md
    - Keyring: src/infisical/credentials/keyring_handler.md 
  - Resource APIs:
    - Base: src/infisical/resources/base.md
    - Secrets: src/infisical/resources/secrets/index.md
    - Folders: src/infisical/resources/folders/index.md
    - Certificates: src/infisical/resources/certificates/index.md
  - Exceptions: src/infisical/exceptions.md
  - Types: src/infisical/_types.md

plugins:
- mkdocstrings:
    default_handler: python_xref
    handlers:
      python_xref:
        import:
        - https://docs.python.org/3/objects.inv
        options:
          docstring_style: google
          show_bases: true
          heading_level: 2
          summary: false
          ignore_init_summary: false
          show_root_heading: false
          show_root_toc_entry: false
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          inherited_members: true
          members_order: source
          show_labels: true
          show_docstring_modules: false
          show_docstring_attributes: true
          show_docstring_examples: true
          show_docstring_parameters: true
          show_docstring_raises: true
          show_docstring_returns: true
          show_docstring_warns: true
          show_docstring_yields: true
          annotations_path: brief
          show_signature_annotations: true
          line_length: 80
          separate_signature: true
          show_signature: true
          signature_crossrefs: true
          unwrap_annotated: true
          relative_crossrefs: true
          check_crossrefs: yes
          
theme:
  name: material
  icon:
    logo: material/file-check-outline
  include_sidebar: true
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.top
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - content.code.annotate
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - tables
  - toc:
      title: On this page
      permalink: true
      toc_depth: 3
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
