[GLOBAL]
pants_version = "2.25.0"
backend_packages = [
    "pants.backend.python",
    "pants.backend.experimental.python",
    "pants.backend.experimental.python.lint.ruff.check",
    "pants.backend.experimental.python.lint.ruff.format",
    "pants.backend.shell",
    "pants.backend.shell.lint.shfmt",
    "pants.backend.shell.lint.shellcheck",
    "pants.backend.experimental.adhoc",
]

[anonymous-telemetry]
enabled = false

[cli.alias]
all = "::"
lock = "generate-lockfiles"
venv = "export --py-resolve-format=symlinked_immutable_virtualenv --resolve=python-default"
gendocs = "scripts/generate_github_pages.py"
mkdocs = ":mkdocs"
mkdocs-serve = ":mkdocs-serve"

[source]
root_patterns = [
    "src",
    "/",
]

[python]
interpreter_constraints = [">=3.11"]
enable_resolves = true

[test]
use_coverage = true

[pytest]
install_from_resolve = "python-default"
